"""Repository initialization: detect profiles, write `.ai/`, render adapters."""

from __future__ import annotations

import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

import typer
import yaml

from kcia.config import model_in_catalog, resolve_agents
from kcia.git.flow import (
    CURRENT_BRANCH,
    GITFLOW,
    GitFlow,
    detect_branches,
    load_flow,
    save_flow,
)
from kcia.git.repo import GitError, current_branch, is_git_repo, known_branches
from kcia.paths import control_plane_root, find_repo_root
from kcia.profiles.bundle import write_bundle, write_if_changed
from kcia.profiles.detector import DetectionHit, detect
from kcia.profiles.inheritance import resolve_inheritance
from kcia.profiles.loader import load_registry
from kcia.project_index import build_project_facts
from kcia.render import render_template

# `.ai/local/`, `.ai/cache/` and `.ai/generated/` are regenerable from
# `kcia start`, so none of them belong in the project's history. `.ai/history/`
# is the opposite: it is the durable session log (`kcia session log`) and is
# meant to be committed, so it is deliberately left out of this list.
GIT_CONFIG_FILE = ".ai/local/git.yaml"

GITIGNORE_MARKER = "# kcia — generated, do not commit"
GITIGNORE_ENTRIES = (
    ".ai/local/",
    ".ai/cache/",
    ".ai/generated/",
    # Local repo-scoped profiles: shared via `kcia profile add`, not via git.
    ".ai/profiles/",
    "CLAUDE.md",
    "AGENTS.md",
    ".cursor/rules/",
    # May carry per-server headers; it is regenerated by `kcia mcp add`.
    ".cursor/mcp.json",
)


def interactive() -> bool:
    """Whether there is a human to answer a question."""
    return sys.stdin.isatty()


def init(
    yes: bool = typer.Option(
        False, "--yes", "-y", help="Accept all high-confidence detections without asking."
    ),
    path: Path | None = typer.Option(
        None, "--path", help="Repository to initialize (default: current directory)."
    ),
    no_gitignore: bool = typer.Option(
        False, "--no-gitignore", help="Do not touch the project's .gitignore."
    ),
    refresh_context: bool = typer.Option(
        False,
        "--refresh-context",
        help="Regenerate .ai/context/project.md, discarding local edits to it.",
    ),
    gitflow: bool | None = typer.Option(
        None,
        "--gitflow/--no-gitflow",
        help="Branch every task off a development branch, or work on the current one.",
    ),
    main_branch: str | None = typer.Option(
        None, "--main-branch", help="Name of the main branch (skips the question)."
    ),
    develop_branch: str | None = typer.Option(
        None, "--develop-branch", help="Name of the development branch (skips the question)."
    ),
) -> None:
    """Initialize `.ai/` and generated adapters in the current repository."""
    repo_root = (path or find_repo_root() or Path.cwd()).resolve()
    if not repo_root.is_dir():
        typer.echo(f"not a directory: {repo_root}")
        raise typer.Exit(code=1)

    registry = load_registry(repo_root)
    if not registry.profiles:
        typer.echo("No profiles available. Check the control plane installation.")
        raise typer.Exit(code=1)

    hits = detect(repo_root, registry)
    if not hits:
        typer.echo(
            "No profiles detected. Add a profile under `.ai/profiles/` or run "
            "`kcia profile scaffold <id>`."
        )
        raise typer.Exit(code=1)

    accepted = _resolve_ambiguities(hits, interactive=not yes and interactive())
    entries = _manifest_entries(accepted)

    written: list[Path] = []
    written += _write_manifest(repo_root, entries)
    written += _write_context(
        repo_root,
        layout="monorepo" if len(entries) > 1 else "single",
        refresh=refresh_context,
    )
    written += _write_bundles(repo_root, registry, entries)
    written += _write_adapters(repo_root, registry, entries)
    if not no_gitignore:
        written += _update_gitignore(repo_root)

    typer.echo(f"Initialized {repo_root}")
    for entry in entries:
        typer.echo(f"  {entry['id']}\t{', '.join(entry['roots'])}")
    if written:
        typer.echo(f"{len(written)} file(s) written.")
    else:
        typer.echo("Already up to date.")

    _configure_git_flow(
        repo_root,
        interactive=not yes and interactive(),
        gitflow=gitflow,
        main_branch=main_branch,
        develop_branch=develop_branch,
    )
    _report_agents(repo_root)


def _configure_git_flow(
    repo_root: Path,
    *,
    interactive: bool,
    gitflow: bool | None,
    main_branch: str | None,
    develop_branch: str | None,
) -> None:
    """Decide the branching model once, here, so no run ever has to ask.

    Detection is used to make the question cheap — `main` and `develop` are read
    off the real branches — but the answer is the user's, and it is only asked
    when the repository does not already make it obvious.
    """
    typer.echo("")
    typer.echo("Git flow")
    if not is_git_repo(repo_root):
        typer.echo("  Not a git worktree yet, so branching is off. Re-run `kcia start` after")
        typer.echo("  `git init` to turn it on.")
        return

    try:
        main_guess, develop_guess = detect_branches(repo_root)
        branches = known_branches(repo_root)
        here = current_branch(repo_root)
    except GitError as exc:
        typer.echo(f"  Could not read the branches ({exc}); leaving branching off.")
        return

    existing = load_flow(repo_root)
    flags_given = gitflow is not None or main_branch or develop_branch
    if existing.configured and not flags_given:
        typer.echo(f"  Already configured: {existing.describe()}.")
        typer.echo(f"  Change it in {GIT_CONFIG_FILE}.")
        return

    if not branches:
        typer.echo("  This repository has no branches yet (no commits), so branching is off.")
        save_flow(repo_root, GitFlow(flow=CURRENT_BRANCH, configured=True))
        return

    resolved_main = main_branch or main_guess.name
    resolved_develop = develop_branch or develop_guess.name

    if interactive:
        use_flow, resolved_main, resolved_develop = _ask_git_flow(
            gitflow, resolved_main, resolved_develop, branches, here
        )
    else:
        # Non-interactive: an explicit flag wins, otherwise git flow is on only
        # when the repository already has a development branch to base it on.
        use_flow = gitflow if gitflow is not None else bool(resolved_develop)

    if not use_flow:
        save_flow(
            repo_root,
            GitFlow(
                flow=CURRENT_BRANCH,
                main_branch=resolved_main,
                develop_branch=resolved_develop,
                configured=True,
            ),
        )
        typer.echo(f"  No git flow: each task is worked on the branch you are on (`{here}`).")
        typer.echo(f"  Change it in {GIT_CONFIG_FILE}.")
        return

    base = resolved_develop or resolved_main
    if not base:
        typer.echo("  No development or main branch found, so branching is off.")
        save_flow(repo_root, GitFlow(flow=CURRENT_BRANCH, configured=True))
        return

    save_flow(
        repo_root,
        GitFlow(
            flow=GITFLOW,
            main_branch=resolved_main,
            develop_branch=resolved_develop,
            base_branch=base,
            configured=True,
        ),
    )
    typer.echo(f"  Git flow: every task branches off `{base}`, automatically.")
    if resolved_main:
        typer.echo(f"  Main branch: `{resolved_main}`.")
    typer.echo(f"  Change it in {GIT_CONFIG_FILE}.")


def _ask_git_flow(
    gitflow: bool | None,
    main_guess: str | None,
    develop_guess: str | None,
    branches: list[str],
    here: str,
) -> tuple[bool, str | None, str | None]:
    """The one interactive moment. Everything after this follows the answer."""
    if develop_guess or main_guess:
        found = ", ".join(f"`{name}`" for name in (main_guess, develop_guess) if name)
        typer.echo(f"  Found {found} in this repository (local and remote).")
    else:
        typer.echo("  No `main`/`master` or `develop` branch found.")
    typer.echo("")

    if gitflow is None:
        typer.echo(f"  1. Git flow — each task opens its own branch off `{develop_guess or main_guess or here}`")
        typer.echo(f"  2. No git flow — each task is worked on the current branch (`{here}`)")
        typer.echo("")
        answer = typer.prompt("  Which one?", default="1").strip()
        use_flow = not answer.startswith("2")
    else:
        use_flow = gitflow

    if not use_flow:
        return False, main_guess, develop_guess

    main = _ask_branch("  Main branch", main_guess, branches, allow_empty=True)
    develop = _ask_branch("  Development branch", develop_guess or main, branches, allow_empty=True)
    return True, main, develop


def _ask_branch(
    label: str, default: str | None, branches: list[str], *, allow_empty: bool
) -> str | None:
    while True:
        answer = typer.prompt(label, default=default or "").strip()
        if not answer:
            if allow_empty:
                return None
            continue
        if answer in branches:
            return answer
        typer.echo(f"    `{answer}` is not a branch here. Known: {', '.join(branches[:8])}")
        if not typer.confirm("    Use it anyway?", default=False):
            continue
        return answer




def _report_agents(repo_root: Path) -> None:
    """Show which agents will run, or how to choose them.

    Agents are what actually execute the waves, so an unconfigured repo would
    otherwise only discover the defaults when a run is already under way.
    """
    resolved = resolve_agents(repo_root)
    unset = [role for role, item in resolved.items() if item.origin == "default"]
    typer.echo("")
    if unset:
        typer.echo("No agents configured yet — waves would run on catalog defaults:")
        for role in unset:
            item = resolved[role]
            typer.echo(f"  {role}: {item.provider}/{item.model}")
        typer.echo("Set them before running the pipeline:")
        typer.echo("  kcia agent models                       see the options")
        typer.echo("  kcia agent set planner claude --model <id>")
        typer.echo("  kcia agent set builder cursor --model <id>")
        return

    typer.echo("Agents:")
    stale = False
    for role, item in resolved.items():
        typer.echo(f"  {role}: {item.provider}/{item.model} ({item.origin})")
        if not model_in_catalog(item.provider, item.model):
            stale = True
            typer.echo(
                f"    warning: `{item.model}` is not offered by `{item.provider}` anymore. "
                f"Run `kcia agent models {item.provider}` and set a valid one."
            )
    if not stale:
        typer.echo("Next: kcia task init \"<what you want>\"")


def _resolve_ambiguities(hits: list[DetectionHit], *, interactive: bool) -> list[DetectionHit]:
    """Keep the best hits per root, asking when a root has several high-confidence ones."""
    by_root: dict[str, list[DetectionHit]] = defaultdict(list)
    for hit in hits:
        by_root[hit.root.as_posix()].append(hit)

    accepted: list[DetectionHit] = []
    for root in sorted(by_root):
        candidates = by_root[root]
        high = [hit for hit in candidates if hit.confidence == "high"]
        chosen = high or _best_per_profile(candidates)
        chosen = _best_per_profile(chosen)

        if len(chosen) > 1 and high and interactive:
            typer.echo(f"\nSeveral profiles match `{root}`:")
            for index, hit in enumerate(chosen, start=1):
                typer.echo(f"  {index}. {hit.profile_id} — {'; '.join(hit.evidence)}")
            answer = typer.prompt(
                "Keep which? (comma-separated numbers, or 'all')", default="all"
            ).strip()
            if answer.lower() != "all":
                picked = []
                for token in answer.split(","):
                    token = token.strip()
                    if token.isdigit() and 1 <= int(token) <= len(chosen):
                        picked.append(chosen[int(token) - 1])
                if picked:
                    chosen = picked
            for hit in chosen:
                accepted.append(_with_resolution(hit, "confirmed"))
            continue

        accepted.extend(_with_resolution(hit, "auto") for hit in chosen)
    return accepted


def _best_per_profile(hits: list[DetectionHit]) -> list[DetectionHit]:
    """Collapse several rules of the same profile at one root to its strongest hit."""
    order = {"high": 3, "medium": 2, "low": 1}
    best: dict[str, DetectionHit] = {}
    for hit in hits:
        current = best.get(hit.profile_id)
        if current is None or order.get(hit.confidence, 0) > order.get(current.confidence, 0):
            best[hit.profile_id] = hit
    return [best[key] for key in sorted(best)]


_RESOLUTIONS: dict[tuple[str, str], str] = {}


def _with_resolution(hit: DetectionHit, resolution: str) -> DetectionHit:
    # DetectionHit is frozen, so the resolution is carried in a side table.
    _RESOLUTIONS[(hit.profile_id, hit.root.as_posix())] = resolution
    return hit


def _root_pattern(root: Path) -> str:
    text = root.as_posix()
    return "**" if text in {".", ""} else f"{text}/**"


def _manifest_entries(hits: list[DetectionHit]) -> list[dict]:
    by_profile: dict[str, dict] = {}
    for hit in hits:
        entry = by_profile.setdefault(
            hit.profile_id,
            {
                "id": hit.profile_id,
                "roots": [],
                "commands": {},
                "detection": {
                    "confidence": hit.confidence,
                    "resolution": _RESOLUTIONS.get(
                        (hit.profile_id, hit.root.as_posix()), "auto"
                    ),
                    "evidence": [],
                },
            },
        )
        pattern = _root_pattern(hit.root)
        if pattern not in entry["roots"]:
            entry["roots"].append(pattern)
        for evidence in hit.evidence:
            if evidence not in entry["detection"]["evidence"]:
                entry["detection"]["evidence"].append(evidence)
    return [by_profile[key] for key in sorted(by_profile)]


def _write_manifest(repo_root: Path, entries: list[dict]) -> list[Path]:
    path = repo_root / ".ai" / "manifest.yaml"
    previous = {}
    if path.is_file():
        previous = yaml.safe_load(path.read_text(encoding="utf-8")) or {}

    version_file = control_plane_root() / "VERSION"
    control_plane_version = (
        version_file.read_text(encoding="utf-8").strip() if version_file.is_file() else "0.0.0"
    )

    manifest = {
        "schema_version": 2,
        "project": {
            "name": repo_root.name,
            "default_profile": entries[0]["id"] if entries else None,
            "layout": "monorepo" if len(entries) > 1 else "single",
        },
        "profiles": entries,
        "dependencies": previous.get("dependencies", []),
        "detection": {
            "exclude_dirs": (previous.get("detection") or {}).get("exclude_dirs", []),
            "last_run": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        },
        "integrations": previous.get(
            "integrations",
            {
                "jira": {"enabled": False, "base_url": None, "project_keys": []},
                "github": {"enabled": True, "allow_open_pr": False, "allow_merge": False},
            },
        ),
        "context": previous.get("context", {"auto_update": True, "requires_active_task": True}),
        "control_plane": {
            "version": control_plane_version,
            "packs": [
                {"name": "kcia-builtin", "version": control_plane_version, "source": "builtin"}
            ],
        },
    }

    # `last_run` changes every run; ignore it when deciding whether anything moved.
    comparable = dict(manifest)
    comparable["detection"] = dict(manifest["detection"])
    comparable["detection"].pop("last_run", None)
    prior = dict(previous)
    if prior:
        prior["detection"] = dict(prior.get("detection") or {})
        prior["detection"].pop("last_run", None)
    if prior == comparable:
        return []

    content = yaml.safe_dump(manifest, sort_keys=False, allow_unicode=True)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return [path]


def _write_context(repo_root: Path, *, layout: str, refresh: bool = False) -> list[Path]:
    templates = control_plane_root() / "templates"
    path = repo_root / ".ai" / "context" / "project.md"
    # The file is yours once it exists: it is the one place to add what only a
    # human knows. `--refresh-context` opts back into the generated version.
    if path.is_file() and not refresh:
        return []

    facts = build_project_facts(repo_root, name=repo_root.name, layout=layout)
    if not facts:
        facts = (
            "## Summary\nUNKNOWN — kcia could not derive the stack from this repository.\n"
            "Describe it here; this section is injected into every wave."
        )
    content = render_template(templates, "project.md.j2", facts=facts)
    return [path] if write_if_changed(path, content) else []


def _write_bundles(repo_root: Path, registry, entries: list[dict]) -> list[Path]:
    written: list[Path] = []
    for entry in entries:
        resolved = resolve_inheritance(entry["id"], registry)
        written.extend(write_bundle(repo_root, resolved, entry["roots"]))
    return written


def _write_adapters(repo_root: Path, registry, entries: list[dict]) -> list[Path]:
    templates = control_plane_root() / "templates" / "adapters"
    written: list[Path] = []
    profiles = [{"id": entry["id"], "roots": entry["roots"]} for entry in entries]

    for name in ("CLAUDE.md", "AGENTS.md"):
        content = render_template(templates, f"{name}.j2", profiles=profiles)
        if write_if_changed(repo_root / name, content):
            written.append(repo_root / name)

    rules_dir = repo_root / ".cursor" / "rules"
    core = render_template(templates / "cursor", "00-core.mdc.j2")
    if write_if_changed(rules_dir / "00-core.mdc", core):
        written.append(rules_dir / "00-core.mdc")

    for index, entry in enumerate(entries, start=1):
        resolved = resolve_inheritance(entry["id"], registry)
        cursor_globs = (resolved.adapters.get("cursor") or {}).get("globs") or ["**/*"]
        globs = _expand_globs(entry["roots"], cursor_globs)
        content = render_template(
            templates / "cursor",
            "profile.mdc.j2",
            profile={
                "id": resolved.id,
                "display_name": resolved.display_name,
                "roots": entry["roots"],
            },
            globs=globs,
        )
        path = rules_dir / f"{index:02d}-{resolved.id}.mdc"
        if write_if_changed(path, content):
            written.append(path)

        if (resolved.adapters.get("claude") or {}).get("nested_file"):
            for root in entry["roots"]:
                directory = repo_root / root.removesuffix("/**")
                if root == "**" or not directory.is_dir():
                    continue
                nested = render_template(templates, "CLAUDE.md.j2", profiles=[
                    {"id": resolved.id, "roots": [root]}
                ])
                if write_if_changed(directory / "CLAUDE.md", nested):
                    written.append(directory / "CLAUDE.md")

    return written


def _expand_globs(roots: list[str], profile_globs: list[str]) -> list[str]:
    globs: list[str] = []
    for root in roots:
        prefix = root.removesuffix("/**")
        for glob in profile_globs:
            combined = glob if root == "**" else f"{prefix}/{glob}"
            if combined not in globs:
                globs.append(combined)
    return globs


def _update_gitignore(repo_root: Path) -> list[Path]:
    """Keep the kcia-managed block of .gitignore in sync with GITIGNORE_ENTRIES.

    The block is replaced wholesale rather than only appended to, so a stale
    entry from an earlier kcia version (e.g. a blanket `.ai/` that would have
    swallowed the git-tracked `.ai/history/`) is dropped on the next run
    instead of lingering forever.
    """
    path = repo_root / ".gitignore"
    existing = path.read_text(encoding="utf-8") if path.is_file() else ""

    if GITIGNORE_MARKER in existing:
        prefix, _, after = existing.partition(GITIGNORE_MARKER)
        # The managed block runs until the next blank line or end of file.
        rest_lines = after.splitlines()
        cut = len(rest_lines)
        for line_index, line in enumerate(rest_lines):
            if line_index > 0 and not line.strip():
                cut = line_index
                break
        suffix = "\n".join(rest_lines[cut:])
    else:
        prefix, suffix = existing, ""

    managed_block = f"{GITIGNORE_MARKER}\n" + "".join(f"{entry}\n" for entry in GITIGNORE_ENTRIES)

    content = prefix.rstrip("\n")
    content += ("\n\n" if content else "") + managed_block
    if suffix.strip():
        content += "\n" + suffix.strip("\n") + "\n"

    if content == existing:
        return []
    path.write_text(content, encoding="utf-8")
    return [path]
