"""Projection of resolved profiles into `.ai/generated/profiles/`."""

from __future__ import annotations

from pathlib import Path

from kcia.profiles.inheritance import ResolvedProfile

GENERATED_HEADER = (
    "<!-- Generated by `kcia init`. Do not edit; edits are lost on the next run. -->\n"
)


def bundle_root(repo_root: Path) -> Path:
    return repo_root / ".ai" / "generated" / "profiles"


def render_bundle(resolved: ResolvedProfile, roots: list[str]) -> dict[str, str]:
    """Build the bundle files for one resolved profile as {relative path: content}."""
    files: dict[str, str] = {}

    summary = [GENERATED_HEADER, f"# {resolved.display_name}\n"]
    summary.append(f"Profile id: `{resolved.id}`\n")
    if resolved.ancestors:
        chain = " -> ".join([*resolved.ancestors, resolved.id])
        summary.append(f"Inheritance: `{chain}`\n")
    if roots:
        summary.append("\n## Roots\n")
        summary.extend(f"- `{root}`\n" for root in roots)
    if resolved.commands:
        summary.append("\n## Commands\n")
        summary.extend(
            f"- `{name}`: `{command}`\n" for name, command in resolved.commands.items()
        )
    if resolved.rules:
        summary.append("\n## Rules\n")
        summary.extend(f"- {name}: {value}\n" for name, value in resolved.rules.items())
    required = resolved.validation.get("required_commands") or []
    if required:
        summary.append("\n## Validation\n")
        summary.append(f"Required before handoff: {', '.join(required)}\n")
    files["profile.md"] = "".join(summary)

    # References are concatenated parent-first, keeping the declaring profile visible
    # so guidance inherited from an ancestor is attributable.
    references = [GENERATED_HEADER, f"# {resolved.display_name} — references\n"]
    for entry in resolved.references:
        references.append(f"\n<!-- from profile: {entry.profile_id} ({entry.path.name}) -->\n")
        references.append(_read(entry.path))
    files["references.md"] = "".join(references)

    for name, path in sorted(resolved.workflows.items()):
        files[f"workflows/{name}"] = GENERATED_HEADER + _read(path)

    return files


def write_bundle(repo_root: Path, resolved: ResolvedProfile, roots: list[str]) -> list[Path]:
    """Write one profile bundle. Returns the paths that actually changed."""
    target = bundle_root(repo_root) / resolved.id
    changed: list[Path] = []
    for relative, content in render_bundle(resolved, roots).items():
        path = target / relative
        if write_if_changed(path, content):
            changed.append(path)
    return changed


def write_if_changed(path: Path, content: str) -> bool:
    """Write only when the content differs, so `kcia init` stays idempotent."""
    if path.is_file() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def _read(path: Path) -> str:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return f"<!-- missing reference: {path} -->\n"
    return text if text.endswith("\n") else text + "\n"
